twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        '%kernel.project_dir%/public/assets/mail': mail
        '%kernel.project_dir%/public/assets/img/logos': logos
        
